const Courses = [
    {
    id: "1",
    title: "Web Development",
    image: require("../../assets/web.jpg"),
    description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.",
    Course1: "HTML",
    Course2: "CSS",
    Course3: "JavaScript",
    price: "5000",
},
{
    id: "2",
    title: "Graphic Designing",
    image: require("../../assets/graphic.jpg"),
    description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.",
    Course1: "Photoshop",
    Course2: "Figma",
    Course3: "Adobe XD",
    price: "3000",
},
{
    id: "3",
    title: "Coding Fundamentals",
    image: require("../../assets/coding.jpg"),
    description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.",
    Course1: "JavaScript",
    Course2: "Algorithm",
    Course3: "Data Structure",
    price: "1000",
},
{
    id: "4",
    title: "Ethical Hacking",
    image: require("../../assets/ethical.jpg"),
    description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.",
    Course1: "Testing",
    Course2: "Exploitation",
    Course3: "Linux OS",
    price: "6000",
},
{
    id: "5",
    title: "Web Development",
    image: require("../../assets/web.jpg"),
    description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.",
    Course1: "html",
    Course2: "css",
    Course3: "javascript",
    price: "4000",
},
{
    id: "6",
    title: "Graphic Designing",
    image: require("../../assets/graphic.jpg"),
    description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.",
    Course1: "PhotoShop",
    Course2: "figma",
    Course3: "AdobeXd",
    price: "3000",
},
];

export default Courses;